#http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  #spring:
#  h2:
#    console:
#      enabled: true
spring:

  datasource:
    #url: "jdbc:h2:file:./data/webshopDb"
   username: ${JDBC_DATABASE_USERNAME}
   password: ${JDBC_DATABASE_PASSWORD}
   url: ${JDBC_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
